/* WS-Routing.h
   Generated by wsdl2h 1.2.0 from WS-Routing.xsd and WS-typemap.dat
   2005-04-03 03:45:09 GMT
   Copyright (C) 2001-2005 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use wsdl2h option -l to view the software license terms.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - To build with STL, stlvector.h from the gSOAP distribution must be in the
   current directory. Or use soapcpp2 option -I<path> with path to stlvector.h.
 - Use typemap.dat to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to typemap.dat to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.

*/

/******************************************************************************\
 *                                                                            *
 * http://schemas.xmlsoap.org/rp/                                             *
 *                                                                            *
\******************************************************************************/

//gsoapopt cw


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

wsrp = http://schemas.xmlsoap.org/rp/

*/

//gsoap wsrp  schema namespace:	http://schemas.xmlsoap.org/rp/
//gsoap wsrp  schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/



/// Schema http://schemas.xmlsoap.org/rp/ simpleType "action_t" restriction of xs:anyURI


/// Schema http://schemas.xmlsoap.org/rp/ simpleType "to_t" restriction of xs:anyURI


/// Schema http://schemas.xmlsoap.org/rp/ simpleType "from_t" restriction of xs:anyURI


/// Schema http://schemas.xmlsoap.org/rp/ simpleType "id_t" restriction of xs:anyURI


/// Schema http://schemas.xmlsoap.org/rp/ simpleType "relatesTo_t" restriction of xs:anyURI


/// Schema http://schemas.xmlsoap.org/rp/ simpleType "faultcode_t" restriction of xs:integer


/// Schema http://schemas.xmlsoap.org/rp/ simpleType "faultreason_t" restriction of xs:string


/// Schema http://schemas.xmlsoap.org/rp/ complexType "path_t"

struct wsrp__path_USCOREt
{
/// Element reference "http://schemas.xmlsoap.org/rp/":action
    char*                                wsrp__action                   1;	///< Required element
/// Element reference "http://schemas.xmlsoap.org/rp/":to
    char*                                wsrp__to                       0;	///< Optional element
/// Element reference "http://schemas.xmlsoap.org/rp/":fwd
    struct wsrp__fwd_USCOREt*            wsrp__fwd                      0;	///< Optional element
/// Element reference "http://schemas.xmlsoap.org/rp/":rev
    struct wsrp__rev_USCOREt*            wsrp__rev                      0;	///< Optional element
/// Element reference "http://schemas.xmlsoap.org/rp/":from
    char*                                wsrp__from                     0;	///< Optional element
/// Element reference "http://schemas.xmlsoap.org/rp/":id
    char*                                wsrp__id                       0;	///< Optional element
/// Element reference "http://schemas.xmlsoap.org/rp/":relatesTo
    char*                                wsrp__relatesTo                0;	///< Optional element
/// Element reference "http://schemas.xmlsoap.org/rp/":fault
    struct wsrp__fault_USCOREt*          wsrp__fault                    0;	///< Optional element
// TODO: <anyAttribute>
//       Schema extensibility is user-definable
//       Consult the protocol documentation to insert declarations here:
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string
};

/// Schema http://schemas.xmlsoap.org/rp/ complexType "fwd_t"

struct wsrp__fwd_USCOREt
{
/// Size of the dynamic array of struct wsrp__via_USCOREt* is 0..unbounded
    int                                  __sizevia                     ;
/// Pointer to array of struct wsrp__via_USCOREt*
    struct wsrp__via_USCOREt*           *wsrp__via                      0;
// TODO: <anyAttribute>
//       Schema extensibility is user-definable
//       Consult the protocol documentation to insert declarations here:
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string
};

/// Schema http://schemas.xmlsoap.org/rp/ complexType "rev_t"

struct wsrp__rev_USCOREt
{
/// Size of the dynamic array of struct wsrp__via_USCOREt* is 0..unbounded
    int                                  __sizevia                     ;
/// Pointer to array of struct wsrp__via_USCOREt*
    struct wsrp__via_USCOREt*           *wsrp__via                      0;
// TODO: <anyAttribute>
//       Schema extensibility is user-definable
//       Consult the protocol documentation to insert declarations here:
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string
};

/// Schema http://schemas.xmlsoap.org/rp/ complexType "found_t"

struct wsrp__found_USCOREt
{
/// Size of the dynamic array of char* is 0..unbounded
    int                                  __sizeat                      ;
/// Pointer to array of char*
    char*                               *at                             1;
// TODO: <anyAttribute>
//       Schema extensibility is user-definable
//       Consult the protocol documentation to insert declarations here:
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string
};

/// Schema http://schemas.xmlsoap.org/rp/ complexType "fault_t"

struct wsrp__fault_USCOREt
{
/// Element reference "http://schemas.xmlsoap.org/rp/":faultcode
    char*                                wsrp__faultcode                1;	///< Required element
/// Element reference "http://schemas.xmlsoap.org/rp/":faultreason
    char*                                wsrp__faultreason              1;	///< Required element
/// Element endpoint of type xs:anyURI
    char*                                endpoint                       0;	///< Optional element
/// Element found of type "http://schemas.xmlsoap.org/rp/":found_t
    struct wsrp__found_USCOREt*          found                          0;	///< Optional element
/// Element maxsize of type xs:integer
    int*                                 maxsize                        0;	///< Optional element
/// Element maxtime of type xs:integer
    int*                                 maxtime                        0;	///< Optional element
/// Element retryAfter of type xs:integer
    int*                                 retryAfter                     0;	///< Optional element
// TODO: <anyAttribute>
//       Schema extensibility is user-definable
//       Consult the protocol documentation to insert declarations here:
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string
};

/// Schema http://schemas.xmlsoap.org/rp/ complexType "via_t"

struct wsrp__via_USCOREt
{
    char*                                __item                        ;
/// Attribute vid of type xs:anyURI
   @char*                                vid                            0;	///< Optional attribute
};

/* End of WS-Routing.h */
